#!/bin/bash

echo "🚀 Quick GitHub Upload Script"
echo "=============================="

echo "📋 Steps to upload your portfolio:"
echo ""
echo "1. Go to: https://github.com/new"
echo "2. Repository name: ecomerce"
echo "3. Description: Full-stack eCommerce application with React frontend and Node.js backend"
echo "4. Make it PUBLIC"
echo "5. DON'T initialize with README (we have one)"
echo "6. Click 'Create repository'"
echo ""
echo "7. Then run these commands:"
echo "   git remote set-url origin https://github.com/raja416/ecomerce.git"
echo "   git push -u origin main"
echo ""
echo "🎯 Your portfolio will be live at: https://github.com/raja416/ecomerce"
echo ""
echo "📁 Your project is ready with:"
echo "   ✅ 77 files committed"
echo "   ✅ Professional README"
echo "   ✅ Complete eCommerce app"
echo "   ✅ Clean code structure"
echo ""
echo "💡 Alternative: Use any repository name you want, just update the URL!"
